language: python
python:
  - 3.6
before_install:
  - sudo apt-get update
  - sudo apt-get install -y enchant
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -r requirements-testing.txt
  - python manage.py collectstatic
script:
  - coverage run -m unittest
after_success:
  - coveralls