language: python
python:
  - 3.6
install:
  - pip install coveralls
  - pip install -r requirements.txt
  - python manage.py collectstatic
script:
  - coverage run python -m unittest
after_success:
  - coveralls