# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=8)),
                ('comment_id', models.CharField(max_length=8, unique=True)),
                ('length', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
